### ISSUE TITLE
My Weekend ToDo List

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/mts-dylib-reference#7]
Let's get this thing a bit more finished. So

- [x] Channel based Tuning tables
- [x] Note Filtering
- [x] More extensive tests, including a 2 process test
- [x] Linux cores out running the basic test if IPC is forced off. Why?
- [x] Run the tests in CI
- [x] Skip IPC with a getenv on Mac/Lin
- [x] Cmake argument to build without IPC support on unixen

**Comment by baconpaul** [comment]
OK large swaths of this are done. Definitely a way better implementation this morning than last night.

@narenratan if you wanna run a test at head on your platforms that would be great.

Just one item left for me here (multi-processes tests in the IPC case in CI) and I'm pencils down on this again for a year or two :)

**Comment by baconpaul** [comment]
OK this one is all wrapped up.

Only thing left is windows shmem. That's actually not that hard just I don't have windows where I'm coding this weekend. Will look next week.
